# Site
repository: hanhyur/hanhyur.github.io

# Personal info
name: 한선우
title: 서버 백엔드 엔지니어
email: sunwoohan.me@gmail.com

# Social links
github_username:  hanhyur

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: 
about_content: | # this will include new lines to allow paragraphs
   Java & Spring 기반의 3년차 서버 백엔드 개발자로 코드를 구현하는데 있어 다양한 면을 고민하고, 이를 서비스에 녹여 내어 
  지속 가능한 구조를 지향합니다.<br/>
  <mark>사용자 우선의 서비스</mark>를 개발을 해야한다는 생각을 가지고 있으며, 기술의 개선보다 기술을 통해 고객 중심의 
  비즈니스 문제를 해결하고자 합니다.<br/>
  프로젝트의 비즈니스 배경을 충분히 이해하고, 기획 상의 미흡한 점을 명확히 하여 완성도 있는 서비스를 만들기 위해 노력합니다.

# Experience Section
# experience_title: Experience

# Projects Section
# projects_title: Projects

# Education Section
# educaton_title: Education

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
